// <auto-generated />
using System;
using CarDealership.OrderService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarDealership.OrderService.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20220213125144_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CarDealership.OrderService.Data.CarOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CarModelId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CarOrders");
                });

            modelBuilder.Entity("CarDealership.OrderService.Data.CarOrderOption", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CarOptionId")
                        .HasColumnType("int");

                    b.Property<int?>("CarOrderId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CarOrderId");

                    b.ToTable("CarOrderOption");
                });

            modelBuilder.Entity("CarDealership.OrderService.Data.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CarDealership.OrderService.Data.CarOrder", b =>
                {
                    b.HasOne("CarDealership.OrderService.Data.Customer", "Customer")
                        .WithMany("CarOrders")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CarDealership.OrderService.Data.CarOrderOption", b =>
                {
                    b.HasOne("CarDealership.OrderService.Data.CarOrder", "CarOrder")
                        .WithMany("CarOrderOptions")
                        .HasForeignKey("CarOrderId");

                    b.Navigation("CarOrder");
                });

            modelBuilder.Entity("CarDealership.OrderService.Data.CarOrder", b =>
                {
                    b.Navigation("CarOrderOptions");
                });

            modelBuilder.Entity("CarDealership.OrderService.Data.Customer", b =>
                {
                    b.Navigation("CarOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
